# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 5
b = 9
sum = a + b
print(sum)

14


# 3.Define a list and replicate in three different ways.

In [3]:
listik = [1, 2, 3]
#1
print(listik[:])
#2
listt = list(listik)
print(listt)
#3
import copy
new_list1 = copy.copy(listik)
print(new_list1)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


# 4.Define two lists and merge them together.

In [4]:
listik_1 = [1, 2, 3]
listik_2 = [4, 5, 6]
LIST = listik_1 + listik_2

# 5. Get the last element of the list and print it.

In [6]:
listik = [1, 2, 3]
print (listik[len(listik) - 1])

3


# 6.Define a tuple that contains only one element.

In [7]:
tupler = (1)

# 7.Define a three-line long string.

In [8]:
filt = """first line
second line
third line"""
print(filt)


first line
second line
third line


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [9]:
tupler = (1, "red", 3.14)
for x in tupler:
    print (x)

1
red
3.14


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [10]:
def Mul(x, y):
    return x * y
Mul(7, 98)

686

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [11]:
import numpy as np
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [12]:
import numpy as np
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [13]:
import numpy as np
x = np.arange(15)
x = x.reshape (3,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [15]:
import numpy as np
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3)
C = A * B
print(C)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
